Prism.languages.lsf = {
	'comment': [
		{
			pattern: /\/\/.*/,
			greedy: true
		},
		{
			pattern: /\/\*[\s\S]*?\*\//
		}
	],
	'string': {
		pattern: /'(\\'|\\\\|[^\n\r'])*'/,
		greedy: true,
	},
	'keyword': /\b(?:BOOLEAN|TBOOLEAN|BPISTRING|BPSTRING|COLOR|CSVFILE|CSVLINK|DATE|DATETIME|INTERVAL|DOUBLE|EXCELFILE|EXCELLINK|FILE|HTMLFILE|HTMLLINK|IMAGEFILE|IMAGELINK|INTEGER|ISTRING|JSONFILE|JSONLINK|LINK|LONG|NAMEDFILE|NUMERIC|PDFFILE|PDFLINK|DBFFILE|DBFLINK|RAWFILE|RAWLINK|RICHTEXT|STRING|TABLEFILE|TABLELINK|TEXT|TEXTFILE|TEXTLINK|TIME|WORDFILE|WORDLINK|XMLFILE|XMLLINK|YEAR|ABSTRACT|ACTION|ACTIONS|ACTIVATE|ACTIVE|AFTER|AGGR|ALL|AND|APPEND|APPLY|AS|ASK|ASON|ASYNCUPDATE|ATTACH|ATTR|AUTO|AUTOREFRESH|AUTOSET|BACKGROUND|BCC|BEFORE|BODY|BODYPARAMHEADERS|BODYPARAMNAMES|BODYURL|BOTTOM|BOX|BREAK|BY|CALENDAR|CANCEL|CANONICALNAME|CASE|CATCH|CC|CENTER|CHANGE|CHANGEABLE|CHANGECLASS|CHANGED|CHANGEKEY|CHANGEMOUSE|CHANGEWYS|CHARSET|CHARWIDTH|CHECK|CHECKED|CLASS|CLASSCHOOSER|CLIENT|CLOSE|COLLAPSE|COLUMN|COLUMNS|COMPLEX|CONCAT|CONFIG|CONFIRM|CONNECTION|CONSTRAINT|CONSTRAINTFILTER|CONTAINER|CONTAINERH|CONTAINERV|CONTEXTMENU|CONTINUE|COOKIES|COOKIESTO|CSV|CUSTOM|CYCLES|DATA|DB|DBF|DEFAULT|DEFAULTCOMPARE|DELAY|DELETE|DESC|DESIGN|DIALOG|DISABLE|DISABLEIF|DO|DOC|DOCKED|DOCX|DOWN|DRAW|DRAWROOT|DRILLDOWN|DROP|DROPCHANGED|DROPPED|ECHO|EDIT|ELSE|EMAIL|EMBEDDED|END|EQUAL|ESCAPE|EVAL|EVENTID|EVENTS|EXCEPTLAST|EXCLUSIVE|EXEC|EXPAND|EXPORT|EXTEND|EXTERNAL|EXTID|EXTKEY|EXTNULL|FALSE|FIELDS|FILTER|FILTERBOX|FILTERCONTROLS|FILTERGROUP|FILTERGROUPS|FILTER|FILTERS|FINALLY|FIRST|FIXED|FLEX|FLOAT|FOCUSED|FOLDER|FOOTER|FOR|FOREGROUND|FORM|FORMEXTID|FORMS|FORMULA|FROM|FULL|GET|GLOBAL|GOAFTER|GRID|GRIDBOX|GROUP|GROUPCHANGE|HALIGN|HEADER|HEADERS|HEADERSTO|HIDE|HIDESCROLLBARS|HIDETITLE|HINT|HINTNOUPDATE|HINTTABLE|HORIZONTAL|HOVER|HTML|HTTP|IF|IMAGE|IMPORT|IMPOSSIBLE|IN|INDEX|INDEXED|INIT|INLINE|INPUT|INTERNAL|IS|JAVA|JOIN|JSON|JSONTEXT|KEYPRESS|LAST|LEFT|LIKE|LIMIT|LIST|LOCAL|LOCALASYNC|LOG|LOGGABLE|LSF|MANAGESESSION|MAP|MATERIALIZED|MATCH|MAX|MEASURE|MEASURES|MEMO|MENU|MESSAGE|META|MIN|MODULE|MOVE|MS|MULTI|NAGGR|NAME|NAMESPACE|NATIVE|NAVIGATOR|NESTED|NESTEDSESSION|NEW|NEWCONNECTION|NEWEDIT|NEWEXECUTOR|NEWSESSION|NEWSQL|NEWTHREAD|NO|NOCANCEL|NOCHANGE|NOCOMPLEX|NOCONSTRAINTFILTER|NODEFAULT|NOENCODE|NOEXTID|NOESCAPE|NOFLEX|NOHEADER|NOHINT|NOINLINE|NOMANAGESESSION|NONULL|NOPREVIEW|NOREPLACE|NOSETTINGS|NOSTICKY|NOT|NOWAIT|NULL|OBJECT|OBJECTS|OK|ON|OPTIMISTICASYNC|OPTIONS|OR|ORDER|ORDERS|OVERRIDE|PAGESIZE|PANEL|PARAMS|PARENT|PARTITION|PASSWORD|PDF|PERIOD|PIVOT|PG|POPUP|POSITION|POST|PREREAD|PREV|PREVIEW|PRINT|PRIORITY|PROPERTIES|PROPERTY|PROPORTION|PUT|QUERYCLOSE|QUERYOK|QUICKFILTER|READ|READONLY|READONLYIF|RECALCULATE|RECURSION|REFLECTION|REGEXP|REMOVE|REPLACE|REPORT|REPORTFILES|REQUEST|REQUIRE|RESOLVE|RETURN|RGB|RIGHT|ROOT|ROUND|ROW|ROWS|RTF|SCHEDULE|SCROLL|SEEK|SELECTED|SELECTOR|SERIALIZABLE|SERVER|SET|SETCHANGED|SETDROPPED|SETTINGS|SHEET|SHOW|SHOWDEP|SHOWIF|SHOWTYPE|SINGLE|SPLITH|SPLITV|SQL|START|STEP|STICKY|STRETCH|STRICT|STRONG|STRUCT|SUBJECT|SUBREPORT|SUCCESS|SUM|TAB|TABBED|TABLE|TAG|TCP|TEXTHALIGN|TEXTVALIGN|TFALSE|THEN|THREADS|TO|TOOLBAR|TOOLBARBOX|TOOLBARLEFT|TOOLBARRIGHT|TOOLBARSYSTEM|TOP|TREE|TRUE|TRY|TTRUE|UDP|UNGROUP|UP|USERFILTER|USERFILTERS|VALIGN|VALUE|VERTICAL|VIEW|WAIT|WARN|WEAK|WHEN|WHERE|WHILE|WINDOW|WITHIN|WRITE|XLS|XLSX|XML|XOR|YES|YESNO|ZDATETIME)\b/,
	'number': /\b\d+\.(?:\d*D?\b)?|\b\d\d:\d\d\b|\b\d{4}_\d\d_\d\d(?:_\d\d:\d\d)?\b|\b\d+L?\b|\b#[0-9a-f]{6}\b/i,
	'operator': /[-+*\/=<>]|!=|<=|==|>=|<-|=>|\+=|###?|\(\+\)|\(-\)/,
	'punctuation': /[;\[\](){},.]/,
	'function': /@[a-zA-Z]\w*\b/,
};